language: java
jdk:
- oraclejdk8
sudo: false
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: XUUAP9CPdaNvOHKSUFzqv86wOrTojAXNGaM4SchePxiFApP35nCeZc6ZJgztNJQkWW65W0no14kfO3Rc1oWXJot5z9MqKlbvD10xP6XL8Fn4uTYxiYX3Yl7Y4Ii5iw7d94sZNLhZMZK9XsnYPFdziLw6uvJnD9JzzZgRiWyQwJqwn922Ddak61lwyjqsaE4TaborLuYV/e1WM4ECauKDdknzQp/97XxxSuZKBj4Mgg6pmXGm6sC+FUxg7PQ90EJl5AyVLT4PHp6GQFrB27fmjuf1jH8+NqigYzjAVoT0O3dR9HbOIqQ/TEdtO8u3Z6rL2Z3RagBhPPyfTwC8NoblmJBT9TPLBR/bdtryiPpOZHbSB36p6y4zqMbbhwTu0kkbzpAht5V8MDPFQSh0z7OFlQQXQ3y7j7NkWn0RfkJkYvJpAn/vlJk0LQxKS3BR+1lk/JnW7BYS3p/M8grotrE8xJtsRvko2xLbM3HF2HoXv9jlX+11Zc6HiHf0fwS/0I0WYrb/h3LX+OoRsPKKSlXd35HmBRtR+ErzdKMn9CJrf1F+kv0ojhN1+A+F9glSmyr6ZoOa0k2f6O4Aps3UwTSClZuijbcODeSe4MY2lJmGNk67b8hkjh+Sr5GtxNZp6liu73cmUoUJBMo+C9sd6eukXVm7Oek4pJ8ApD4gcAnuQPk=
  secret_access_key:
    secure: ljNDuOCGyC4B5nzxXRZWP8om3NN9bfikAAWqsxbBeaSN0t8m6iALmnbRK6kfaAfPIMTqPcajQL8BizunltZQH2laXdfWhlnHPc4ER7DjjJ85G8HhXCGlxROUySgeJlPtiTEYxe9VNhkjtaJgczREe7hkW8nFqhec0fWyU70iB7Nrdzm/F/r5Yr3jnDoaraRBt85lClCiejjYypDb2Gsv6ZjtgXeJBeXllHfRzCcTz4zUqYlQR4hmPikjYCOrS+AjTdR8teWUdTyG2qxNLp94BW4bwmxTVOgHGU5t0xQJm4GDKPdDcqxLSjTkuKBfXVbRXddD57tJ1QbyRu86+BId8jkW1nIlvOrzoUWrvLaSJjaWIV5ACEFuo34ztknTCMJVNS5ev4Fm9X8o7VTTfxlOKYrwdr4bVXi1bQoYwYeNy/wbnSlGmR4ekWhaMwTWRHxrcXRyVlUR/brXwz3DSrzxpiN8b3gYGwSoUEHpYuDYVkHt+6jU/C6s4DfXT7APkoTV1DDW1XpK7fCHcRuXKF5eBeLKDsmUA8iA0XoVsaO0VT5VTl0lpUz6Sdu9u3Ox1ZM2tdXHLEibDjAu0eQSSXcKZ24/Ij3LERcM7pmizmSbfDhsXH4ZYGiXDOAnY+22fuWJMIMcdM4nsoY1VzBDlriej2xPpubtgR1b3k7xqvjy59Q=
  region: us-east-1
  app: Bridge-Reporter
  env:
    develop: Bridge-Reporter-Dev
    uat: Bridge-Reporter-Uat
    prod: Bridge-Reporter-Prod
  bucket_name: elasticbeanstalk-us-east-1-649232250620
  zip-file: target/Bridge-Reporter-1.0.war
  on:
    all_branches: true