language: java
jdk:
- oraclejdk8
sudo: false
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: AKIAI5DSX4HRCDMKR2AQ
  secret_access_key: 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
  region: us-east-1
  app: Bridge-Reporter
  env:
    develop: Bridge-Reporter-Dev
    uat: Bridge-Reporter-Uat
    prod: Bridge-Reporter-Prod
  bucket_name: elasticbeanstalk-us-east-1-649232250620
  zip-file: target/Bridge-Reporter-1.0.war
  on:
    all_branches: true
